# Azure Document Intelligence configuration
AZURE_DOCUMENT_INTELLIGENCE_ENDPOINT=https://necxtek.cognitiveservices.azure.com/
AZURE_DOCUMENT_INTELLIGENCE_KEY=8FHdCbczvUFitwT6aA56GDKIBKe9hnXk0VOfT2nKYrRlwemIWBMUJQQJ99CGACYeBjFXJ3w3AAALACOGQU5k
# Backup key (optional)
AZURE_DOCUMENT_INTELLIGENCE_KEY_2=CqMcaIyzokCBGcnjRE6fDEcpRIvC2WBHIuZeS3VAUi30g9toWXwUJQQJ99CGACYeBjFXJ3w3AAALACOGHZ7r
