package com.nexatek.invoice;

import java.math.BigDecimal;
import java.nio.file.Files;
import java.nio.file.Path;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.time.LocalDate;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import static org.junit.jupiter.api.Assertions.*;

class InvoiceImportRepositoryTest {

    @TempDir Path temporary;

    @Test
    void rollsBackInvoiceItemsMovementAndStockWhenAnyStockUpdateFails() throws Exception {
        try (Connection connection = DriverManager.getConnection("jdbc:h2:mem:rollback;MODE=PostgreSQL;DB_CLOSE_DELAY=-1")) {
            createSchema(connection);
            Path source = temporary.resolve("invoice.pdf");
            Files.write(source, new byte[]{'%', 'P', 'D', 'F'});
            ExtractedInvoice invoice = invoice(source);
            invoice.getItems().add(item(1, "CODE-1"));
            invoice.getItems().add(item(999, "MISSING"));

            InvoiceImportRepository repository = new InvoiceImportRepository(connection, temporary.resolve("stored"));
            assertThrows(java.sql.SQLException.class, () -> repository.receive(invoice, "tester"));
            assertEquals(0, count(connection, "supplier_purchase_invoices"));
            assertEquals(0, count(connection, "supplier_purchase_invoice_items"));
            assertEquals(0, count(connection, "stock_movements"));
            try (ResultSet result = connection.createStatement().executeQuery("select quantity from products where productid=1")) {
                assertTrue(result.next());
                assertEquals(0, new BigDecimal("10").compareTo(result.getBigDecimal(1)));
            }
        }
    }

    private void createSchema(Connection connection) throws Exception {
        try (Statement statement = connection.createStatement()) {
            statement.execute("create table products(productid int primary key,quantity numeric,cost_price numeric)");
            statement.execute("insert into products values(1,10,100)");
            statement.execute("create table supplier_purchase_invoices(id bigint generated by default as identity primary key,supplier_id int,supplier_name varchar,supplier_address varchar,supplier_vat_registration varchar,supplier_tax_id varchar,supplier_phone varchar,document_type varchar,copy_type varchar,invoice_number varchar,invoice_date date,due_date date,sales_order_number varchar,order_date date,ship_date date,salesperson varchar,purchase_order_number varchar,customer_code varchar,customer_name varchar,customer_address varchar,customer_tax_id varchar,customer_phone varchar,shipping_address varchar,shipping_instructions varchar,fiscal_document_number varchar,verification_code varchar,prepared_by varchar,printed_at varchar,checked_by varchar,received_by_name varchar,received_date date,subtotal numeric,discount numeric,freight numeric,miscellaneous_charges numeric,tax numeric,total numeric,currency varchar,extraction_confidence numeric,extraction_timestamp timestamp,approved_by varchar,original_document_path varchar,source_sha256 varchar,corrected_fields varchar)");
            statement.execute("create table supplier_purchase_invoice_items(id bigint generated by default as identity primary key,invoice_id bigint,line_number int,supplier_product_code varchar,supplier_description varchar,warehouse varchar,quantity numeric,unit varchar,unit_price numeric,line_tax numeric,line_discount numeric,line_amount numeric,extraction_confidence numeric,internal_product_id int,matching_status varchar,corrected_fields varchar)");
            statement.execute("create table supplier_product_mappings(id bigint generated by default as identity primary key,supplier_id int,supplier_product_code varchar,supplier_description varchar,internal_product_id int,created_at timestamp default current_timestamp,last_used_at timestamp default current_timestamp)");
            statement.execute("create table stock_movements(id bigint generated by default as identity primary key,product_id int,movement_type varchar,quantity numeric,unit_cost numeric,reference_type varchar,reference_id bigint,movement_timestamp timestamp default current_timestamp,approved_by varchar)");
        }
    }

    private ExtractedInvoice invoice(Path source) {
        ExtractedInvoice invoice = new ExtractedInvoice();
        invoice.setSupplierId(7);
        invoice.setSupplierName("Supplier");
        invoice.setInvoiceNumber("INV-ROLLBACK");
        invoice.setInvoiceDate(LocalDate.of(2026, 7, 10));
        invoice.setSubtotal(new BigDecimal("200"));
        invoice.setTotal(new BigDecimal("200"));
        invoice.setOriginalDocumentPath(source);
        return invoice;
    }

    private ExtractedInvoiceItem item(int productId, String code) {
        ExtractedInvoiceItem item = new ExtractedInvoiceItem();
        item.setSupplierProductCode(code);
        item.setDescription(code);
        item.setQuantity(BigDecimal.ONE);
        item.setUnitPrice(new BigDecimal("100"));
        item.setAmount(new BigDecimal("100"));
        item.setConfidence(0.9);
        item.setMatchedProductId(productId);
        item.setMatchedProductName(code);
        item.setMatchingStatus(ExtractedInvoiceItem.MatchingStatus.MANUAL);
        return item;
    }

    private long count(Connection connection, String table) throws Exception {
        try (ResultSet result = connection.createStatement().executeQuery("select count(*) from " + table)) {
            result.next();
            return result.getLong(1);
        }
    }
}
