/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.nexatek;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author engmartin
 */
public class LOGIN extends javax.swing.JFrame {

Connection conn;
ResultSet rst;
PreparedStatement pst;

    public LOGIN() {
        conn=connection.connect();
        initComponents();
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        loginbtn = new javax.swing.JButton();
        forgot = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nexatek/images/login.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 310, 290));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 520));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 0), 1, true));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Noto Sans", 1, 24)); // NOI18N
        jLabel4.setText("LOGIN FORM ");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, -1, -1));

        username.setBorder(javax.swing.BorderFactory.createTitledBorder("Username"));
        jPanel2.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 430, 60));

        password.setBorder(javax.swing.BorderFactory.createTitledBorder("Password"));
        jPanel2.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 430, 60));

        loginbtn.setBackground(new java.awt.Color(0, 153, 0));
        loginbtn.setFont(new java.awt.Font("Noto Sans", 1, 20)); // NOI18N
        loginbtn.setForeground(new java.awt.Color(255, 255, 255));
        loginbtn.setText("SIGNIN");
        loginbtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        loginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbtnActionPerformed(evt);
            }
        });
        jPanel2.add(loginbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 430, 50));

        forgot.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        forgot.setText("forgot username / password?");
        jPanel2.add(forgot, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 450, 280, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 750, 520));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbtnActionPerformed
//              String sql = "select * from users where username = ? and password =?";
////             String sql2="select * from ADMIN_LOGIN where ID=? and USERNAME=?";
//
//            try{
//            pst = conn.prepareStatement(sql);
//            pst.setString(1, username.getText().trim());
//            pst.setString(2, password.getText().trim());
//
//            rst = pst.executeQuery();
//            
//            if(rst.next()){                  
//                this.setVisible(false);
////                 JOptionPane.showMessageDialog(null, "ALERT!", "YOU ARE UNDER SUPERVISION",5);
//            JOptionPane.showMessageDialog(null,"Welcome.."+username.getText());
//             Home e = new Home();
//            e.setVisible(true);               
//           }
//            else
//            {
//                JOptionPane.showMessageDialog(null, "olimba olimba");
//            }
//            }
//            catch(Exception e){
//                JOptionPane.showMessageDialog(null, e);
//            }


            String sql = "select * from employeestbl where username = ? and password = ?";
            String sql2="select * from administrators where username=? and password=?";
            try{
            pst = conn.prepareStatement(sql);
            pst.setString(1, username.getText().trim());
            pst.setString(2, password.getText().trim());
            rst = pst.executeQuery();
            
            if(rst.next()){                  
                this.setVisible(false);
                 JOptionPane.showMessageDialog(null,"Welcome.."+username.getText());
             counter count = new counter();
             count.pack();
             count.counter.setText(username.getText());
            count.setVisible(true);               
           }
            
            /////////////////////
            pst = conn.prepareStatement(sql2);
            pst.setString(1, username.getText().trim());
            pst.setString(2, password.getText().trim());
            rst = pst.executeQuery();
            if(rst.next()){
                rst.close();
                pst.close();
                this.setVisible(false);
                Home e = new Home();
                e.pack();
                e.counter.setText(username.getText());
                e.setVisible(true); 
                 JOptionPane.showMessageDialog(null, "Welcome... "+username.getText());
                 
           }
           
            }
            catch(Exception e){
                    JOptionPane.showMessageDialog(null, e);                     
                    }
            finally{
            try{
            rst.close();
            pst.close();
            }
            catch(Exception e){} 
            }

            
    }//GEN-LAST:event_loginbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LOGIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel forgot;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton loginbtn;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
