/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.nexatek;

import java.sql.Connection;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author KEVINcustoms
 */
public class reports extends javax.swing.JPanel {
Connection conn;
    /**
     * Creates new form reports
     */
    public reports() {
        conn= connection.connect();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
     public void view_receipt() {
    try {
        JasperDesign jdesign = JRXmlLoader.load("src\\reports\\solditemsrepo.jrxml");
        String query = "select * from solditems where invoice_number = '" + invoice.getText() + "'";
        JRDesignQuery updateQuery = new JRDesignQuery();
        updateQuery.setText(query);
        jdesign.setQuery(updateQuery);

        JasperReport jreport = JasperCompileManager.compileReport(jdesign);
        JasperPrint jprint = JasperFillManager.fillReport(jreport, null, conn);

        // Create a separate JFrame for JasperViewer
        JFrame frame = new JFrame("KEVINcustoms Report Viewer");
        
        // Set the default close operation to DISPOSE_ON_CLOSE
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        // Create and show the JasperViewer within the JFrame
        JasperViewer viewer = new JasperViewer(jprint, false);
        frame.getContentPane().add(viewer.getContentPane());
        frame.setSize(900, 700); // Set the size according to your preference
        frame.setLocationRelativeTo(null); // Center the frame on the screen
        frame.setVisible(true);

    } catch (JRException ex) {
        Logger.getLogger(sales_admin.class.getName()).log(Level.SEVERE, null, ex);
    }
}
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        invoice = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        view_all = new javax.swing.JButton();
        view_all1 = new javax.swing.JButton();

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Invoice NO.");

        invoice.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("View");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        view_all.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        view_all.setText("View All Sales");
        view_all.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_allActionPerformed(evt);
            }
        });

        view_all1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        view_all1.setText("Sub Cost Prices");
        view_all1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_all1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(21, 21, 21)
                .addComponent(invoice, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(view_all)
                .addGap(26, 26, 26)
                .addComponent(view_all1)
                .addContainerGap(123, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(view_all, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(view_all1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(invoice, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(582, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        view_receipt();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void view_allActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_allActionPerformed
        // TODO add your handling code here:
        try {
        JasperDesign jdesign = JRXmlLoader.load("src\\reports\\solditemsrepo.jrxml");
        String query = "select * from solditems";
        JRDesignQuery updateQuery = new JRDesignQuery();
        updateQuery.setText(query);
        jdesign.setQuery(updateQuery);

        JasperReport jreport = JasperCompileManager.compileReport(jdesign);
        JasperPrint jprint = JasperFillManager.fillReport(jreport, null, conn);

        // Create a separate JFrame for JasperViewer
        JFrame frame = new JFrame("KEVINcustoms Report Viewer");
        
        // Set the default close operation to DISPOSE_ON_CLOSE
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        // Create and show the JasperViewer within the JFrame
        JasperViewer viewer = new JasperViewer(jprint, false);
        frame.getContentPane().add(viewer.getContentPane());
        frame.setSize(900, 700); // Set the size according to your preference
        frame.setLocationRelativeTo(null); // Center the frame on the screen
        frame.setVisible(true);

    } catch (JRException ex) {
        Logger.getLogger(sales_admin.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_view_allActionPerformed

    private void view_all1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_all1ActionPerformed
        // TODO add your handling code here:
         try {
        JasperDesign jdesign = JRXmlLoader.load("src\\reports\\sub_cost_prices_repo.jrxml");
        String query = "select * from sub_cost_price inner join products on sub_cost_price.product_name = products.name";
        JRDesignQuery updateQuery = new JRDesignQuery();
        updateQuery.setText(query);
        jdesign.setQuery(updateQuery);

        JasperReport jreport = JasperCompileManager.compileReport(jdesign);
        JasperPrint jprint = JasperFillManager.fillReport(jreport, null, conn);

        // Create a separate JFrame for JasperViewer
        JFrame frame = new JFrame("KEVINcustoms Report Viewer");
        
        // Set the default close operation to DISPOSE_ON_CLOSE
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        // Create and show the JasperViewer within the JFrame
        JasperViewer viewer = new JasperViewer(jprint, false);
        frame.getContentPane().add(viewer.getContentPane());
        frame.setSize(900, 700); // Set the size according to your preference
        frame.setLocationRelativeTo(null); // Center the frame on the screen
        frame.setVisible(true);

    } catch (JRException ex) {
        Logger.getLogger(sales_admin.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_view_all1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField invoice;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton view_all;
    private javax.swing.JButton view_all1;
    // End of variables declaration//GEN-END:variables
}
