/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.nexatek;

import java.awt.Component;
import javax.swing.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.NumberFormat;
import java.util.Collections;
import java.util.List;
import java.util.Locale;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import java.awt.*;
import javax.swing.table.DefaultTableCellRenderer;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author KEVINcustoms
 */
public class Statistics_table extends javax.swing.JFrame {
Connection conn;
    PreparedStatement pst;
    ResultSet rst;
    DefaultTableModel model;
    private StatisticsService statisticsService;
    private List<StatisticsService.ProfitRow> profitRows = Collections.emptyList();
    /**
     * Creates new form Statistics_table
     */
    public Statistics_table() {
        conn = connection.connect();
        initComponents();
        statisticsService = new StatisticsService(conn);
        profitsCalculation();
        addProfits();
        
    }
    
    
       public void profitsCalculation() {
        if (conn == null) {
            JOptionPane.showMessageDialog(this, "Database connection failed. Statistics cannot be loaded.");
            return;
        }

        try {
            profitRows = statisticsService.loadProfitRows();
            model = statisticsService.createTableModel(profitRows);
            statisticstbl.setModel(model);
            statisticstbl.setAutoCreateRowSorter(true);
            statisticstbl.setRowHeight(26);
            statisticstbl.setDefaultRenderer(Object.class, new CustomCellRenderer());
        } catch (SQLException ex) {
            Logger.getLogger(Statistics_table.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Unable to load statistics: " + ex.getMessage());
        }

        // Revalidate and repaint the frame to show the updated UI
        revalidate();
        repaint();
    }

    static class CustomCellRenderer extends DefaultTableCellRenderer {
        private static final Color PROFIT_ROW = new Color(220, 255, 220);
        private static final Color PROFIT_CELL = new Color(62, 190, 96);
        private static final Color NO_PROFIT_ROW = new Color(255, 225, 225);
        private static final Color NO_PROFIT_CELL = new Color(225, 78, 78);

        public CustomCellRenderer() {
            setOpaque(true);
        }

        @Override
        public Component getTableCellRendererComponent(JTable table2, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            super.getTableCellRendererComponent(table2, value, isSelected, hasFocus, row, column);
            if (isSelected) {
                setBackground(table2.getSelectionBackground());
                setForeground(table2.getSelectionForeground());
            } else {
                int modelRow = table2.convertRowIndexToModel(row);
                int modelColumn = table2.convertColumnIndexToModel(column);
                Object profitValue = table2.getModel().getValueAt(modelRow, 7);
                double profit = profitValue instanceof Number ? ((Number) profitValue).doubleValue() : 0;

                boolean hasProfit = profit > 0;
                if (modelColumn == 7) {
                    setBackground(hasProfit ? PROFIT_CELL : NO_PROFIT_CELL);
                    setForeground(Color.WHITE);
                } else {
                    setBackground(hasProfit ? PROFIT_ROW : NO_PROFIT_ROW);
                    setForeground(Color.BLACK);
                }
            }
            return this;
        }
    }
    public void addProfits(){
        double sum = statisticsService == null ? 0 : statisticsService.totalPositiveProfit(profitRows);
        totalprofits.setText(NumberFormat.getNumberInstance(Locale.US).format(sum));
    }
    
    public void sendData(){
    if (profitRows.isEmpty()) {
        JOptionPane.showMessageDialog(this, "There is no statistics data to save.");
        return;
    }
    try {
        statisticsService.saveProfitSnapshot(profitRows);
        JOptionPane.showMessageDialog(this, "Data inserted successfully");
    } catch (SQLException ex) {
        Logger.getLogger(Statistics_table.class.getName()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(this, "Unable to save statistics: " + ex.getMessage());
    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        statisticstbl = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        totalprofits = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("STATISTICS TABLE FOR LUCKY ELECTRICALS");

        statisticstbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(statisticstbl);

        jLabel2.setText("TOTAL PROFITS MADE");

        totalprofits.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N

        jButton1.setText("Save Snapshot");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalprofits, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(33, 33, 33)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1020, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalprofits, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        sendData();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        java.awt.EventQueue.invokeLater(() -> new Statistics_table().setVisible(true));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable statisticstbl;
    private javax.swing.JLabel totalprofits;
    // End of variables declaration//GEN-END:variables

}
